### ISSUE TITLE
webpack error about "digraph-sort"

### ISSUE THREAD

**Issue by tiagochen** [ToddFincannon/digraph-sort#1]
Hi Todd:
   Thanks for your npm package "digraph-sort" , it make my work more easier.
   But "digraph-sort" can not used in browser, beacuse "index.js" line 1 is : #!/usr/bin/env node, could you please fixed it?
   Thank you so much.
   ps: webpack error: "Module parse failed: Unexpected character '#' (1:0)"

**Comment by ToddFincannon** [comment]
I removed the bash shebang and updated dependencies too in commit 920f15d.
